// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu1XV_1Mhr5i4A_fY6MP2jMQBf_7b8O04',
    appId: '1:905312702990:web:553f6325be6f33122ee25f',
    messagingSenderId: '905312702990',
    projectId: 'sem-5-a0d79',
    authDomain: 'sem-5-a0d79.firebaseapp.com',
    storageBucket: 'sem-5-a0d79.firebasestorage.app',
    measurementId: 'G-YH05QBCVC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_5eWhnQoYArKRX0i_1e_pGbFPnBa0zH4',
    appId: '1:905312702990:android:e6c6f95fd100f9502ee25f',
    messagingSenderId: '905312702990',
    projectId: 'sem-5-a0d79',
    storageBucket: 'sem-5-a0d79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAag9I7bjiLgOw78JITJBkx0WA5B4geTUI',
    appId: '1:905312702990:ios:e405576407f162e42ee25f',
    messagingSenderId: '905312702990',
    projectId: 'sem-5-a0d79',
    storageBucket: 'sem-5-a0d79.firebasestorage.app',
    iosBundleId: 'com.example.sem5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAag9I7bjiLgOw78JITJBkx0WA5B4geTUI',
    appId: '1:905312702990:ios:e405576407f162e42ee25f',
    messagingSenderId: '905312702990',
    projectId: 'sem-5-a0d79',
    storageBucket: 'sem-5-a0d79.firebasestorage.app',
    iosBundleId: 'com.example.sem5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu1XV_1Mhr5i4A_fY6MP2jMQBf_7b8O04',
    appId: '1:905312702990:web:d7d61223035581e82ee25f',
    messagingSenderId: '905312702990',
    projectId: 'sem-5-a0d79',
    authDomain: 'sem-5-a0d79.firebaseapp.com',
    storageBucket: 'sem-5-a0d79.firebasestorage.app',
    measurementId: 'G-KZ7M7N20HD',
  );

}